### PR TITLE
Add support for loading homebrew under a title, for backwards compatbility

### PR DESCRIPTION
**Pull request by Wack0**
Some people (including myself) have been annoyed at the lack of backcompat for some older homebrew, so I decided to do the work for this myself.

This requires hbmenu support to use this, I will be also sending a PR their way.

This adds a few new hb:ldr commands. Loader uses them to check if it's running a title to takeover, if so it copies a small loader over codebin start that loads the 3dsx (talking to hb:ldr) in a similar way to *hax (again, the point of this is backwards compatibility).

I have tested svdt and a few others, which work successfully.

### CODE REVIEW

**Comment by Wack0** [comment]
For reference, here's the new-hbmenu PR: https://github.com/fincs/new-hbmenu/pull/26

**Comment by fincs** [comment]
What is the point of this? 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. Is there any reason why CIA versions of savegame managers can't be used? This is also not going to make HANS work for instance (which is completely obsoleted by Luma3DS's built-in game patching feature). Likewise, you can use GodMode9 instead of braindump for dumping game assets.

**Comment by Wack0** [comment]
Backwards compatibility is the point.

(Oh, also, you mentioned HANS; it does work with this PR.)

**Comment by fincs** [comment]
Why do you want to maintain backwards compatibility with applications for which there exist better and more up-to-date alternatives? This only brings unnecessary complexity and code cruft to Rosalina.

**Comment by Wack0** [comment]
Because some people prefer to use the old applications.

**Comment by urherenow** [comment]
there are some early homebrew that don't play nice with Rosalina and are not being worked on, such as ctrhexenII and 3dscraft, etc... If someone else has done the work and it doesn't actually break anything, I fail to see why it should be rejected.

**Comment by Plailect** [comment]
It makes little sense in my mind to maintain backwards compatibility for no reason other than "because some people prefer to use the old applications" if it requires unnecessary complexity to be added.

**Comment by urherenow** [comment]
It's NOT because "some people prefer". It's because some homebrew has been abandoned and "users" are not capable of updating them to work with b9s/Rosalina

**Comment by fincs** [comment]
> such as ctrhexenII and 3dscraft, etc...

> "users" are not capable of updating them to work with b9s/Rosalina

That has nothing to do with target title support and everything to do with the fact that these applications haven't been developed in a long time, and they cannot be compiled with the latest tools and libraries. You could have instead worked on fixing these applications to work with the latest software...

**Comment by profi200** [comment]
If this gets merged i would recommend adding a switch to switch between the new 3dsx loading system and backwards compatibility. The new one should definitely be default.

**Comment by Wack0** [comment]
@profi200 the new 3dsx loading system *is* default; backwards compatibility is only used when required.

**Comment by profi200** [comment]
How do you detect if it is needed? (Did not look through all the changes in detail.)

**Comment by Wack0** [comment]
@profi200 if a target title is set in hb:ldr, next launch of that title will use the backward compatible 3dsx loading.

**Comment by profi200** [comment]
Ok. And what if you launch a compatible app after launching a incompatible one? Is that case handled?

**Comment by TuxSH** [comment]
The only kind of homebrew which would benefit from this PR would be HANS (which is totally redundant with Luma's own features and also massively outdated) and outdated save managers (just use jksv).

About other homebrew applications: all it takes is building them with latest ctrulib. It is the responsibility of the contributors to those homebrew applications to do so, not ours.

**Comment by Wack0** [comment]
Yes, the target title gets cleared after launch.

**Pull request closed without merging**
