### PR TITLE
Screencap improvements and old forks

### PR DESCRIPTION
**Pull request by therealbungus**
- Convert to JPG instead of using BMP using tinyjpeg

- Choose which screen to save for screenshot (both default, hold L for top and R for bottom)

- Save screenshot filename as date/time (format YYYY-MM-DD_HH-MM.SS.jpg)
The above change means that screenshots save very fast now, from ~6 seconds to ~1 second (also fixes #937 )

credit to streetwalrus for most of the code for converting the images to JPG

Improvements:

- could inform the user what screen is being saved using the "screen" variable 
- use 24 hour time for sorting and in case of overwrites

### CODE REVIEW

**Comment by frozenLake** [comment]
JPG? D:

can we have a toggle for that?

**Comment by therealbungus** [comment]
It could be implemented by a setting or something, all the old code for
saving as bmp can be run with an if statement by calling for a variable
that the user can change with the setting. Not sure where I would store
that variable though

**Comment by urherenow** [comment]
When did use of the z buttons become a thing in homebrew?

**Comment by therealbungus** [comment]
https://github.com/AuroraWright/Luma3DS/issues/487
Was looking for some info saying otherwise, but I guess I didn't look hard enough.

**Comment by zoogie** [comment]
I would have used lodepng but that's just me.

**Comment by therealbungus** [comment]
@zoogie 
notepad _2017-12-14_21-23-36
Kind of large isn't it 😛 

https://github.com/elanthis/upng

Found a derivative of lodePNG that is much smaller, will take a look at it tonight

Heres another that also looks much smaller than both https://www.nayuki.io/page/tiny-png-output-c

**Comment by therealbungus** [comment]
Looks like tinypngout is the best lib for doing this, and png would be a much better alternative than jpg.

**Comment by fincs** [comment]
JPG is a *terrible* format for screenshots. It is a lossy format (which is unacceptable), intended for photographs. PNG is the only format that should be used for screenshots.

**Comment by ghost** [comment]
@fincs is right; BMP and PNG are really the only options here, though hopefully WebP takes off eventually.

**Comment by fincs** [comment]
From tiny-png-output-c website:

> In ~260 lines of code, this library implements these key components: PNG header writer, PNG chunk writer, **DEFLATE uncompressed encoder** (...)

The part in bold renders this library useless, since it doesn't actually compress the image data.

**Pull request closed without merging**
