### PR TITLE
"Friends" and "ErrDisp" patches (and Makefile fix)

### PR DESCRIPTION
**Pull request by TuxSH**
This pull request fixes some build issues.

It also patches the "friends" module, my changing the `fdpver` to 5 (if it's less). I didn't patch ACT however, as it would break at the next NVer update.

The "ErrDisp" patches makes it [more verbose](https://cdn.pbrd.co/images/2EzDXpe.jpg) even on retail firmwares, however keep in mind that "on retail consoles, the system does not notify ErrDisp that any user-land exceptions occurred, ErrDisp is only notified for this on dev/debug units" (3dbrew).

### CODE REVIEW

**Comment by damnnfo** [comment]
I downloaded the code from https://github.com/TuxSH/AuReiNand.
Then I tried to compile it.
But unfortunately I got an error msg as below:
make[1]: _**No rule to make target 'launcher'.   Stop
make: *_\* [out/AuReiNand.dat] Error 2

**Comment by damnnfo** [comment]
But "make a9lh" was working fine

**Comment by TuxSH** [comment]
@damnnfo Make sure you have the latest versions of bin2c, armips and [makerom](https://github.com/profi200/Project_CTR/tree/master/makerom) under your PATH.

Use `make clean` as well.

**Comment by damnnfo** [comment]
@TuxSH It's working now. Thank you for your support.

**Pull request merged**
