### PR TITLE
Implemented Kasai07's features and improved stability.

### PR DESCRIPTION
**Pull request by ghost**
I added a massive shitload of stuff. Too many to list!

### CODE REVIEW

**Comment by ghost** [comment]
We have no interest in integrating "RosalinaMod". "RosalinaMod" integrates a bunch of features we have rejected in the past, and additionally messes up the memory map quite a bit. Additionally, there's a bunch of nonsense commits in here, like repeating the LED off/on commands in sysconfig.c just with "40" switched for "0x28".

**Comment by ghost** [comment]
Geez.. Just trying to help. If you're going to reject anything I try to help with, then be that way. Don't know why you hackers in the 3ds community need to be little shits to me.

**Comment by noirscape** [comment]
If I can dispense any useful advice here, either make your commits more descriptive rather than "edited file here/added files by upload" or include actual information in the PR about what and why you changed it. Nobody wants to sift through tons of code to figure out what you changed (especially since you seem to have made a large number of arbitrary changes for no discernible reason).

**Comment by ghost** [comment]
And finally, the coup de grace.
REVENGE
https://docs.google.com/document/d/1N1N8XBUP4mZABLEWaoxjMmcpISN50z_fqkC0W3w0r38/edit?usp=sharing

**Comment by ihaveamac** [comment]
have you thought about the fact that maybe the contribution just wasn't useful? you may be trying to help and that's nice, but that doesn't mean what you do has to be accepted. don't take it personally.

**Comment by TuxSH** [comment]
> And how did you become a collaborator anyway? I'll bet you hacked.

She's a trusted person who has been managing issues for quite a while, which we are really grateful for that. If she had hacked anything here, we would have known...

**Pull request closed without merging**
