### PR TITLE
Add install CIA and Explorer

### PR DESCRIPTION
**Pull request by kasai07**
Hello,
I added at rosalina code  an option.
I added the CIA installation and a file explorer.
The explorer allows to search a .cia to install.

Thanks for Luma3ds and your work on the 3ds scene.

cordially.
sorry for my English.

### CODE REVIEW

**Comment by ghost** [comment]
Your english is understable , don't worry

**Comment by ghost** [comment]
Hi there. Thanks for this, but CIA installation is really out of scope for Rosalina; it's more appropriate for FBI which can be ran as a 3DSX if you do not want to use it as a installed CIA. However, the file explorer is useful, thank you for implementing that; we may utilize it or parts of it in the future.

**Comment by kasai07** [comment]
Uh...... the code for the installation of cia works

**Comment by kasai07** [comment]
https://www.youtube.com/watch?v=WvqoPZ9Gmqc&list=PLDsSayCvgIr9WlgPmmyNeKYs2t-rnl_od&index=1

**Comment by coc4tm** [comment]
It's "not appropriate" ...

**Comment by v0idst4r** [comment]
File exploring is appropriate for CTRXplorer

**Comment by ValShaped** [comment]
@kasai07 The CIA installation feature is something that was debated on, and it was decided that it would not become a feature of Rosalina. Thank you for implementing it though! It was worth a try.

**Comment by kasai07** [comment]
@ValliantStorme  so stay with your principles. ^-^

**Comment by Margen67** [comment]
Maybe this could be made into a plugin if those are ever implemented

**Comment by piratesephiroth** [comment]
Yeah it looks like a great feature.
Let's hope the plugin system isn't denied as well.

**Comment by coc4tm** [comment]
A plug-in wouldn't be so easy to do ...

**Pull request closed without merging**
