### PR TITLE
removing -flto flag

### PR DESCRIPTION
**Pull request by codeM-X**
removing -flto to fix compiler error (windows 10 + gcc 8.2.1 (mingw) 12/12/2018)

### CODE REVIEW

**Comment by urherenow** [comment]
This is actually a gcc bug (specifically in the required binutils), and removing -flto may not be the correct answer. I’m not sure because I don’t know why it’s specifically used here...

With that said, this bug report should be submitted to the DKP team, as it was fixed for gcc 8.1 back in July...

**Comment by profi200** [comment]
I second that. It's a GCC bug. Removing -flto is a workaround. The other option is running the Linux variant of devkitARM inside WSL.

**Comment by urherenow** [comment]
Or ubuntu in vmware player (free) to avoid cluttering your system drive...

**Comment by Dimensional** [comment]
How is this not cluttering up the hard drive as much as the other
option? I'm sure when you use the dynamic allocation of the vmdk, it'll
take up the same amount of space, if not more since the WSL has things
removed due to missing kernel features, none that should affect
devkitpro, not to mention no need for guest additions for shared folders.

**Comment by Dimensional** [comment]
How is this not cluttering up the hard drive as much as the other option? I'm sure when you use the dynamic allocation of the vmdk, it'll take up the same amount of space, if not more since the WSL has things removed due to missing kernel features, none that should affect devkitpro, not to mention no need for guest additions for shared folders.

**Comment by urherenow** [comment]
I’m operating under the assumption that most people have more than 1 hdd, or at least more than 1 partition. WSL adds thousands of files deep in the C: drive tree and clutters it up. Especially impactful if you’re smart enough to utilize imaging software to keep updated images of your C: drive in case of crashes/malware/etc...

**Comment by Dimensional** [comment]
Yes, there is that. It's one of the cons and pros between Virtualization
and WSL. But to many that isn't a key problem for them. Still, whatever
works best and easiest.

Some people may not have quite powerful enough systems for a compiler
inside a Virtual Machine, where WSL uses the windows system natively and
as such has less overhead, while others find using a virtual machine has
better compatibility with certain linux only calls that haven't been
translated by WSL. Whichever achieves the overall goal is how I play my
cards, even though I personally use both.

**Pull request closed without merging**
