### PR TITLE
Add a Rosalina System Configuration option to disable the power button short press

### PR DESCRIPTION
**Pull request by izzy84075**

### CODE REVIEW

**Comment by izzy84075** [comment]
Adds the feature I requested yesterday. :) https://github.com/AuroraWright/Luma3DS/issues/752#issuecomment-508606674

**Comment by TuxSH** [comment]
Hey :). Does it disable forced-poweroff (POWER button held for around 12s)?

**Comment by izzy84075** [comment]
Sorry, guess the name could have been more descriptive.

No, this just disables the "power button short press" interrupt from the MCU, which triggers the "Software closed"/"In Sleep Mode, the system can..." screen. Holding the power button will still trigger the forced shutdown.

**Comment by moronigranja** [comment]
Any way to make this setting permanent, or reapplied after boot?

**Pull request merged**
