### PR TITLE
Advanced Config + Power Options menu

### PR DESCRIPTION
**Pull request by cooolgamer**
This pr adds a "advanced_settings" option on the config.ini hidden on the config menu that, if enabled, restores the following options on the luma config menu:
- Enable development UNITINFO,
- Disable ARM11 Exception loaders,
- Enable Rosalina on SAFE_FIRM.

It also adds a "Power Options" menu in the rosalina menu, instead of having "Reboot" and "Power Off" separated, they are both inside this menu and can be called by pressing X to power off and Y to reboot.

### CODE REVIEW

**Comment by PabloMK7** [comment]
Could you elaborate on the benefits of this over the existing implementation?

**Comment by cooolgamer** [comment]
It's just to clean the Rosalina menu a little bit as it have many options, this would just remove one from the main menu but it's better than nothing, it can also prevent accidental "A" presses after selecting one of those.

**Comment by PabloMK7** [comment]
Hello, can you move each feature to it's own PR?

**Comment by profi200** [comment]
Before you put in the effort for another pull request: I remember Luma devs saying they don't want these hidden config options easily available because noobs tend to change them and then complain if something breaks.

**Comment by cooolgamer** [comment]
Yes and this is why the "advanced options" setting that unlock those options in the luma config is hidden so you have to manually edit the config.ini to show them on the luma config, just like the same way you enable those hidden options

**Comment by profi200** [comment]
That's fine i guess.

**Comment by cooolgamer** [comment]
closing this, I'm going to make 2 different pr

**Pull request closed without merging**
