### PR TITLE
Switch to APT_ResetHardwareAsync() for reboot (Closes #831)

### LINKED ISSUE #831: Rosalina reboot - HOME menu ignores latest focused tile
**System model:**
Old 3DS
[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**
11.5.0-38E SysNAND
[e.g. 11.4.0-37U SysNAND, 11.4.0-37J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap/Sighax
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
8.1.1
[e.g. 8.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (1)

Splash: (Before)

PIN lock: (Off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
If shutting down the 3DS with either the hardware button or the `Power off` setting inside Rosalina, the HOME menu will display the last focused tile on the next boot.

If rebooting the device by means of Rosalina's `Reboot` setting, though, the HOME menu won't display the last focused tile upon reboot, showing the one before the last instead.

It would appear to me that rebooting via Rosalina doesn't let the HOME menu save the last tile, but I'm unsure whether this is either desired behavior or non-fixable.

**Steps to reproduce:**

1. When inside the HOME menu, note down the currently focused tile (for example, **System Settings**).

2. Power off the 3DS either by using the hardware button or with Rosalina's `Power off` setting.

3. Boot the 3DS, and note that the HOME menu displays the same focused tile noted down on step 1 (i.e. **System Settings**).

4. Change your focus to another tile (for example, **Nintendo 3DS Sound**).

5. Reboot the handheld via Rosalina's `Reboot` setting.

6. Note that the HOME menu still displays the focused tile noted down on step 1 (i.e. **System Settings**), while we expected it to focus on the one noted down on step 4 (i.e. **Nintendo 3DS Sound**).

**Dump file:** no dump file available.

### PR DESCRIPTION
**Pull request by astronautlevel2**
Also changes the `40` to `0x28` in sysconfig.c for consistency.

### CODE REVIEW

**Comment by fincs** [comment]
I don't think this works at all. APT is not available in Rosalina - it is not even initialized. I expect this to crash.

**Comment by astronautlevel2** [comment]
This does work - I [tested it on my console](https://drive.google.com/file/d/189NtsFZKBoRIblF2hht5KvAuHmI1kAAC/view?usp=sharing) (sorry about the terrible video quality).

This is just speculation as you know far more about libctru than I do, but I'm guessing that when Rosalina exits the APT thread picks up the hardware reset signal and does the reboot then.

**Comment by fincs** [comment]
Heh, I'm surprised. The [APT lock handle](https://github.com/smealum/ctrulib/blob/master/libctru/source/services/apt.c#L122) is uninitialized...

**Comment by AnalogMan151** [comment]
For the love of god, compress that before you upload it. But it does indeed seem to work.

**Comment by profi200** [comment]
Nice. Better than the ugly hack of using svcKernelSetState() (that also may corrupt data in certain cases).

**Comment by Derek1199** [comment]
this does trigger an errdisp screen though(tested on my console) but it automatically reboots anyway.

**Pull request merged**
