### PR TITLE
Added Power Options menu

### PR DESCRIPTION
**Pull request by cooolgamer**
This pr adds a "Power Options" menu in the rosalina menu, instead of having "Reboot" and "Power Off" separated, they are both inside this menu and can be called by pressing X to power off and Y to reboot.
This is to cleanup the Rosalina menu a bit and avoid accidental "A" presses after selecting "reboot" or "power off"

### CODE REVIEW

**Comment by kry008** [comment]
Now is easier, why put inside other menu? But your changes are working for my console

**Comment by Minionguyjpro** [comment]
> This pr adds a "Power Options" menu in the rosalina menu, instead of having "Reboot" and "Power Off" separated, they are both inside this menu and can be called by pressing X to power off and Y to reboot. This is to cleanup the Rosalina menu a bit and avoid accidental "A" presses after selecting "reboot" or "power off"

Maybe we can add new options. Maybe we can also add an option to reboot into the Luma3DS configuration menu without needing to press any buttons at boot? Like using command prompt on Windows to reboot into UEFI firmware settings without you needing to time pressing the BIOS key on boot but just directly booting into it.

**Comment by impeeza** [comment]
It's this still needed on the latest rosalina menues?

**Comment by TuxSH** [comment]
Not interested

**Pull request closed without merging**
