### PR TITLE
update fs.c to look for more payload locations

### PR DESCRIPTION
**Pull request by eip618**
the intention of this is to remove one of the most common, possibly _the_ most common, issue that new users have when setting up luma

### CODE REVIEW

**Comment by PabloMK7** [comment]
This presents new issues, like users having duplicate payloads in different folders. I don't think it's a good idea.

**Comment by eip618** [comment]
> This presents new issues, like users having duplicate payloads in different folders. I don't think it's a good idea.

1. as i understand it, the function should stop at the first valid folder found
2. while what you say is technically correct, i don't believe it would happen often enough to be a concern. what is a concern, however, is people doing insanely stupid things when the console doesn't boot gm9, for example, like deleting everything off the sd card and trying to hack it again and ending up bricking it. this at least would allow them to boot gm9 and would expedite troubleshooting for NH

**Comment by ihaveamac** [comment]
A better idea would probably be to create an empty payloads folder to help reduce the amount of typos people make when trying to create the folder.

**Comment by profi200** [comment]
I don't see this being useful. It may even make support harder when you have to deal with confused people and then multiple folder names on top.

I second the idea of just creating the proper folder or including it in the releases.

**Comment by TuxSH** [comment]
I don't think it is a good idea to support multiple folders

> creating the proper folder

I can do this

**Comment by eip618** [comment]
sorry.

**Comment by TuxSH** [comment]
No need to apologize for this, this is a legitimate concern.

I think I'll have Luma3DS create the payload folder during the "upgrade process", and then implement this before the next release.

**Comment by ManiacOfGitHub** [comment]
> I think I'll have Luma3DS create the payload folder during the "upgrade process", and then implement this before the next release.

Was this done?

**Pull request closed without merging**
