### PR TITLE
Fixes issue #680

### LINKED ISSUE #680: mcu errors if LED state changes >16 times while Rosalina is open
**System model:**

New 3DS (XL)

**SysNAND version (+emu/redNAND version if applicable):**

11.1.0-34U SysNAND, 9.2-something EmuNAND (no longer actively in use)

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.2

**Luma3DS version:**

8.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( 1 )

Screen brightness: ( 2 )

Splash: ( Off )

PIN lock: ( Off )

New 3DS CPU: ( Clock+L2 )

--

Autoboot EmuNAND: ( Off )

Use EmuNAND FIRM if booting with R: ( Off )

Enable loading external FIRMs and modules: ( Off )

Use custom path: ( **I remain unsure that this feature still even exists in current builds** )

Enable game patching: ( On )

Show NAND or user string in System Settings: ( On )

Show GBA boot screen in patched AGB_FIRM: ( On )

Patch ARM9 access: ( Off )

Set developer UNITINFO: ( Off )

--

**Explanation of the issue:**

Changing the LED state 17 times while Rosalina is open causes mcu to throw an error. I can't confirm this works for all LED changes, but the most convenient one to check is the charging LED.

**Steps to reproduce:**

1. Plug/unplug power repeatedly, changing LED state 16 times.

2. Plug/unplug for the 17th time.

**Dump file:**
No dump file, I assume because it's an error, not a crash. Presumably some kind of overflow?

```
An error occurred (ErrDisp)

Error type:       generic

Process ID:       11
Process name:     mcu
Process title ID: 0x0004013000001f02

Address:          0x0010366c
Error code:       0xd8606408
```

### PR DESCRIPTION
**Pull request by hax0kartik**

### CODE REVIEW

**Comment by TuxSH** [comment]
What are notification id 0x400 and 0x401; why block all notifications and not just 0x20D and 0x20E?

**Comment by hax0kartik** [comment]
Oh shit. I had forgotten to commit that file, anyways, 0x401 and 0x400 are notifications that rosalina publishes on `menuEnter` and `menuLeave`, 0x400 sets the flag hasRosalinaMenuStarted to true and hence all the notifs which will be published by `srvPublishToSuscriber` gets skipped

**Comment by hax0kartik** [comment]
> why block all notifications and not just 0x20D and 0x20E? 

'cause there are many other notifs which can cause the same issue.

**Review by uyjulian — COMMENTED** [review]
The indentation seems to be different.

**Comment by ghost** [comment]
Were you able to reproduce the/a similar crash with any other notifications besides `0x20D` and `0x20E`? If not, it may be unwise to simply discard *all* notifications, they are usually posted for a reason and it could leave the system in a messed up state.

**Comment by hax0kartik** [comment]
@Hikari-chin @TuxSH On rechecking once again, I found that only 0x20D and 0x20E caused this issue. Thanks for pointing out.

**Comment by TuxSH** [comment]
Oh sorry about 0x400 and 0x401, I forgot

Anyways, I forgot to mention -- you should replace the `hasRosalinaMenuStarted` logic by checks for `(rosalinaState & 1)`

**Comment by hax0kartik** [comment]
@TuxSH, not sure if I get you.

**Comment by Grindbone** [comment]
hey everyone, can I ask you for help? my girlfriend bought me a 3ds xl a few years ago, and now I wanted to install the R4 B9S card... It did well with the official tutorial from the R4 site until point 18. where it comes to Rosalina... my 3ds froze, then I wanted to restart the tutorial, and put down the files from my internal card, and now I can't switch it on again! I guess it doesn't find the right boot.firm, but I don't have any other right data on my sd card I guess! can you tell me which files I need, I hope I have them on my computer! 
I hope you can help me, because my girlfriend is already pissed! :/ Thanks
If it works, I'm willing to donate money via paypal!

**Comment by urherenow** [comment]
@Grindbone Github is not a support forum. Please download the latest release of Luma3DS and use those files. Read the documents. Read https://3ds.guide/ . If you still need help, post on gbatemp, maxconsole, or Discord.

**Comment by 6100m** [comment]
CHILL @Hikari-chin

**Pull request closed without merging**
