### PR TITLE
Print commit in settings

### PR DESCRIPTION
**Pull request by mariogamer2**

### CODE REVIEW

**Comment by astronautlevel2** [comment]
You should probably squash these commits (generally typo style commits should be squashed in PRs).

**Comment by TuxSH** [comment]
I consider this as a good idea (except for stable releases), personally.
What do you think of it @AuroraWright ?

**Comment by usagirei** [comment]
Might want to add the _--match_ option command on the git describe, just in case for some reason you ever need to make a tag not starting with v for example:

v5.5
r1
r2
...

`git describe --tags --match v[0-9]*`

Will still pull v5.5 instead of the rxxx ones

**Comment by mariogamer2** [comment]
Must be good.

**Comment by usagirei** [comment]
If you take out the --abbrev=0 it'll show the first 8 digits from the commit hash, not sure if it was intentional (as to show v5.x-########), but i'll assume it was since you changed the name to "revision" from "version"

**Comment by TuxSH** [comment]
It should be good.

Thank you both for your contribution.

**Pull request merged**
