### PR TITLE
Added Chainloader

### PR DESCRIPTION
**Pull request by kasai07**
I'm sorry for the other pull request.
I made a cleaner fork.

### CODE REVIEW

**Review by urherenow — COMMENTED** [review]
Bad description. Luma3DS already has a chainloader.  What exactly are you trying to do? Have you built this and it has your desired result? What happens when there is no bootonce.firm on your SD card with this build? What do you use on the 3DS to copy a selected .firm file to bootonce.firm, so it will load on reboot? If you're talking FTP or card swap, why not just use the chainloader that's already there?

Edit: now that I think about it, a way to copy a .firm file to (e.g. x_myfirm.firm) will do the same thing, just requiring you to hold the button on reboot.

**Comment by kasai07** [comment]
An option in rosalina to launch the firms.
it avoids restarting the 3ds.
from there we choose directly what we want to launch.
the bootonce is supported by luma.

**Comment by kasai07** [comment]
from there we choose directly what we want to launch

**Comment by urherenow** [comment]
Loading a firm does restart, even if you're not using the power button. Heck, exiting system settings restarts. You can't simply load a .firm on top of another .firm...

**Comment by Derek1199** [comment]
^^^^^^^ yes. The .firms are arm9 payloads, therefore it requires using arm9, basically early boot to launch a payload. By the time you are able to use rosalina, everything related to arm11 has already launched. You still have to restart in order to boot the .firm, this is useless.

**Comment by profi200** [comment]
It just copies a FIRM to mem and reboots into it. Only benefit is it's quick. I don't see this belonging in Rosalina because there are other solutions that do the exact same.

**Comment by fincs** [comment]
This doesn't "copy a FIRM to mem and reboots into it". This makes a duplicate copy of the FIRM on the SD card, placing it at bootonce.firm, reboots, has Luma read back that file from the SD card, deletes the file and finally launches it. The writing/deleting is a terrible solution as it puts unnecessary strain on the SD card and the FAT filesystem. For that reason alone I think this PR should be rejected.

The proper way to implement this feature would be to inject a small structure (containing the path of the file to launch) in RAM persistent across reboots, which would later be detected by Luma3DS during boot.

**Comment by kasai07** [comment]
@profi200 @fincs 

yes there are other ways to do it.
but either it's a CFW or it's not a CFW.

Adding functions is the goal of a CFW.
if not, stop improving it.

**Comment by fincs** [comment]
>but either it's a CFW or it's not a CFW.
> Adding functions is the goal of a CFW.
> if not, stop improving it.

This makes no sense. If you are going to add a function, either implement it properly or don't do it; as it would decrease the quality of said CFW.

**Comment by ghost** [comment]
@fincs is right here. Additionally, the commits are just all around messy and inconsistent.

**Comment by kasai07** [comment]
@Hikari-chin 
I'm not asking you to go on my fork.
just add this your to options.
improved if you must with the commit you want.

for sure, I am not expert in commits. :-)

I am not looking for my name in your CFW.
 
Je propose des petites options c'est tout.

**Pull request closed without merging**
