### PR TITLE
InputRedirection: fix freeze and improve stability

### LINKED ISSUE #648: Entering or exiting sleep mode while Rosalina menu is up doesn't work
**System model:**

New 3DS (XL)

**SysNAND version (+emu/redNAND version if applicable):**

11.1.0-34U SysNAND, 9.2-something EmuNAND (no longer actively in use)

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.2

**Luma3DS version:**

8.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( 1 )

Screen brightness: ( 2 )

Splash: ( Off )

PIN lock: ( Off )

New 3DS CPU: ( Clock+L2 )

--

Autoboot EmuNAND: ( Off )

Use EmuNAND FIRM if booting with R: ( Off )

Enable loading external FIRMs and modules: ( Off )

Use custom path: ( ? does this feature even exist any more, I don't see it or use it )

Enable game patching: ( On )

Show NAND or user string in System Settings: ( On )

Show GBA boot screen in patched AGB_FIRM: ( On )

Patch ARM9 access: ( Off )

Set developer UNITINFO: ( Off )

--

**Explanation of the issue:**
The Rosalina menu suppresses both entering and exiting sleep mode.

**Steps to reproduce:**
**Entering sleep mode:**
1. Open Rosalina menu using defined shortcut

2. Close 3DS (presumably also works with 2DS sleep switch but I don't know one of those) and notice 3DS is not sleeping (light from screen is still visible in low light environments), etc.

**Exiting Sleep Mode:**
1. Sleep the 3DS (have Rosalina menu NOT open)
2. Enter the Rosalina shortcut (probably easier to do if you change the shortcut to e.g. L+R first, but I'm able to hit L+D-Pad Down + Select with the N3DSXL "almost closed" and keep it sleeping,
3. Re-open (un-switch on 2DS?) the 3DS and notice 3DS is still sleeping.
4. Press B to exit Rosalina, which wakes the 3DS.

This is a dumb bug, I don't think people are likely to encounter it often.

### PR DESCRIPTION
**Pull request by Nanquitas**
- Check for Internet connection before launching the Input Redirection
- Check if the 3DS is going to sleep (through notifications) to pause the threads (close Rosalina menu if open when going to sleep)
- If the Input Redirection is enabled and the 3DS is disconnected from Internet, the Input Redirection will auto exit and wait until the 3DS is connected again before restarting the Input Redirection
- Changed when the patchs are applied as you could remove them when you wanted to apply them and vice-versa depending on the errors you had

Should fix #648, #904 and #935  (maybe #812 too but it seems like there's no particular way to test those reports, so I can't be sure).

### CODE REVIEW

**Comment by Nanquitas** [comment]
The second commit should fix #834 (even if I couldn't replicate the crash on my N3DS).
I put the commit on the same PR as it depends on Wifi_IsConnected implemented in the first one.

**Comment by Nanquitas** [comment]
I was asked for a build, so here it is.
Don't hesitate to say if it worked for you or if you still have a sleep issue. :)

[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1658806/boot.zip)

**Comment by DoctorGoat** [comment]
I have been actively trying to get it to mess up by leaving it in sleep mode with input redirection on this build and I haven't had it blackscreen on me.  Nice!

**Comment by Moire9** [comment]
I will test this. That bug I found is weird [#904], what caused it?

**Comment by Xemiru** [comment]
Very minor thing, but you can't `Stop InputRedirection` when you've disconnected from internet. The build seems to work well, otherwise.

Edit: Apparently that was a mislabel, as when internet was back on it acted as `Start` instead of `Stop`. Subsequently, it would not respond to my client until being turned off and back on **twice**.

**Pull request closed without merging**
