### PR TITLE
Add GitHub Actions Build Workflow

### PR DESCRIPTION
**Pull request by Minionguyjpro**
This adds a GitHub Actions workflow which builds the .firm file and adds it into a zip file, which can be used when the release is done. This allows easy building, which saves time so someone doesn't need to do it manually on their computer.

### CODE REVIEW

**Comment by Minionguyjpro** [comment]
I know it is a lot of commits, needed to test a lot, but now it is working.

**Comment by Querela** [comment]
> I know it is a lot of commits, needed to test a lot, but now it is working.

You can use squash all your commits into one (which is also an action that GitHub can do when merging a pull request).

Use `git rebase -i <parent-of-your-first-commit>`, then change all "pick"s to "s"/"squash" starting from your second commit when the editor pops up. Finally use `git push --force`. Note that your own master-branch needs to be unprotected to allow history-rewrites.
The pull-request here will then be updated.

But ... you can also keep it as is and let the owners/maintainers decide how to merge your changes. Changing your history to have only a few commits with your final changes is more of an aesthetic thing but also gives a better overview what happens compared to "Update xyz". But accidents can when rewriting history so be careful.

PS: building and testing scripts for GitHub Actions (or other CIs) is annoying, and often looks like this...

**Comment by Minionguyjpro** [comment]
> > I know it is a lot of commits, needed to test a lot, but now it is working.
> 
> You can use squash all your commits into one (which is also an action that GitHub can do when merging a pull request).
> 
> Use `git rebase -i <parent-of-your-first-commit>`, then change all "pick"s to "s"/"squash" starting from your second commit when the editor pops up. Finally use `git push --force`. Note that your own master-branch needs to be unprotected to allow history-rewrites. The pull-request here will then be updated.
> 
> But ... you can also keep it as is and let the owners/maintainers decide how to merge your changes. Changing your history to have only a few commits with your final changes is more of an aesthetic thing but also gives a better overview what happens compared to "Update xyz". But accidents can when rewriting history so be careful.
> 
> PS: building and testing scripts for GitHub Actions (or other CIs) is annoying, and often looks like this...

Yes, I agree. Will try to make them less now.

**Comment by Minionguyjpro** [comment]
Ok, I guess I squashed the commits.

**Pull request closed without merging**
