### PR TITLE
Now it looks for a global language emulation config

### PR DESCRIPTION
**Pull request by AssisrMatheus**
> Not tested because i don't have how to build it, please test it(but it should work fine)

If didn't find any file with a title ID to emulate a language, tries to find a globalLocaleConfig.txt to work for any other title.

Example:
My 3DS is Japanese(because it's a exclusive version), but I want ALL my games in English and they're loading in JP, so **instead of having a single txt for each title(that take a lot of effort), it uses globalLocaleConfig.txt changing the language for _every game_**. If there's still a title-specific locale, it'll load it instead of global.

### CODE REVIEW

**Comment by AuroraWright** [comment]
Thank you for the contribution, however this is kinda useless, your Japanese games won't boot in English with language emulation (Japanese carts only have Japanese), and US/European games don't have Japanese instead (like 99% of the times, if not always; none of my EU games has Japanese), and thus default to English already.

**Comment by AssisrMatheus** [comment]
I didn't mean carts, even cias. Some US and EUR games have still their JP language(I know you probably know this or this function wouldn't exist). And they're always opening in Japanese because of my system's language(And of course i want to open all of them in my X language, in this case, English). I don't want to make a text file on locale for each game I "install". Its easier to create a single file that'll open all of them in that language, and if i want a different language for an other game, than i create a single locale for that exception

**Comment by AuroraWright** [comment]
Which European/American games retain Japanese? I also had the original DS and EU carts have always been Multi5 (EU, IT, DE, ES, FR), and the US ones Multi3 (EN, ES, FR). Anyway, I think this is not intended usage for the feature. You might be interested in a complete region change (ARN allows you to do it, you can even modify your own SecureInfo_A to a different region and use it as SecureInfo_C, if you need I can make a guide on GBATemp).

**Comment by AssisrMatheus** [comment]
Bravely Default, any Pokemon and Codename STEAM are the games that i have and this is happening. When i used gw in the old times i had to make it boot a US game(through the gw card) to make the 3DS think its US and then play the game i wanted(cia or every other). With this emulation i can just emulate the US language that it'll work. And having a default config that would overwrite every game is pretty handy.

I don't want to change the system's language because i'm learning JP, and this is helping a lot. But sometimes i just want to play and relax, so playing in a language that i'm more familiar with its better

**Comment by mathieulh** [comment]
Zelda Hyrule warriors also forces the Japanese language on you (not that I personally mind)
I rather have a configuration menu that runs on the 3ds (like a helper cia app, booting with Select or a home menu hack) to change the language configuration on a per title basis without having to use a computer.

**Comment by shinji257** [comment]
The new Kirby game might keep Japanese language when it releases in the US/EUR.  It is already multi-lingual and contains English language text in it.

**Comment by Possum** [comment]
@mathieulh 

> I rather have a configuration menu that runs on the 3ds (like a helper cia app, booting with Select or a home menu hack) to change the language configuration on a per title basis without having to use a computer.

I've been working on a utility (cia) that does just that... mostly just to get some familiarity with coding for non-UNIX systems. I'm basing it on FBI since it has all the title listing features. I plan on releasing the code within the next day or two, once it's in a "usable" state.

@mathieulh - just to follow up, I made this thing: https://github.com/Possum/LumaLocaleSwitcher/releases

The UI could use some polish, but it should work well. Please leave any feedback you have in that repository.

**Comment by reiyu13** [comment]
this would actually be useful if someone buys a japanese 3ds but wants to play US games without doing anything else.

**Comment by MP2E** [comment]
@reiyu13 can confirm, I actually have that exact usecase for my JP New 3DS XL and I would find this feature useful. I can understand if it's too niche to implement though.

**Comment by Possum** [comment]
Putting in another vote for this since I am now in the same situation as @reiyu13 - Japanese 3ds (a JP only edition), want to default to "USA EN". I don't want to do a full region change.

A suggestion for the file name, maybe /luma/locales/default.txt would be better (easier to type)?

**Pull request closed without merging**
