### PR TITLE
Synchronize hw watchpoint on all cores

### LINKED ISSUE #697: GDB Stub memory breakpoints not working. (IDA Pro)
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37E

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (off)

PIN lock: (off)

New 3DS CPU: (off)

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

GDB Stub memory watchpoints not working with IDA pro, I can see the desired memory address change with the hex view, but it doesn't break when it changes.

**Steps to reproduce:**
1. Open IDA database.
2. Enable Luma debugger
3. Attach IDA to the current running process.
4. Jump to the desired address.
5. Debugger -> Breakpoints -> Add breakpoint (This will default the breakpoint to Execute)
6. Debugger -> Breakpoints -> Breakpoint list
7. Edit the breakpoint to be Read/Write instead of execute, as it defaults to Execute. (Break option is enabled)
8. The game doesn't break when the memory address is changed/read.

**Dump file:**
N/A

### PR DESCRIPTION
**Pull request by Nanquitas**
With this, hardware watchpoints are finally working on games. Fix #697
This is confirmed working on multiple games on both O3DS & N3DS.

Huge thanks to enler who released his NTR Dex sources. Cause of the issue was found from his code, and the fix is adapted from his code too.

### CODE REVIEW

**Comment by fincs** [comment]
# ( ͡° ͜ʖ ͡°)

**Comment by Monotek18** [comment]
is this what I think it is
( ͡° ͜ʖ ͡°)

**Comment by Dimensional** [comment]
Since I'm not a big programmer yet, I'm unsure what this means.

**Comment by Nanquitas** [comment]
I'm closing this since @TuxSH merged a better code (506b16d).

**Comment by TuxSH** [comment]
Merged into master branch. Thanks a lot for having found the actual issue and solution.

**Pull request closed without merging**
