### PR TITLE
Add ram viewer/editor

### PR DESCRIPTION
**Pull request by LiquidFenrir**
it's in the features document, so I decided to add it. Go in the process list, and press A on a process (only when gdb is off)

~~Doesn't have searching but that would be a nice addition!~~ disregard, it does now!

### CODE REVIEW

**Comment by fincs** [comment]
# ( ͡° ͜ʖ ͡°)

**Comment by Derek1199** [comment]
Can we edit the RAM the GPU is using with this? I wanna see some nice GPU fuckery. ͡° ͜ʖ ͡°

**Comment by LiquidFenrir** [comment]
owo
could this be...searching? yes it is; and it works!
I've encountered a random data abort when testing but couldn't reproduce it, so no idea how to fix it/what went wrong (most probably the searching, because it happened upon pressing A)

Now, the code is kinda dirty so you might want to rewrite it. I tried to follow the code style of the repo, but I'm tired and may have missed some spots. The variable names however are flat, not camelCased.

**Comment by LiquidFenrir** [comment]
Rewrote it to make it simpler to read. Not really sure I succeeded, but it's already better than the previous.

**Comment by piratesephiroth** [comment]
cheat engine when

**Comment by urherenow** [comment]
Not sure I'm seeing this the way it looks on a PC, but I'll assume you know they'll ask you to squash all of your changes into a single commit...

**Comment by LiquidFenrir** [comment]
no, that happens at merge time

**Comment by piratesephiroth** [comment]
Maybe having them all packed in a single commit make it simpler to revert it if something goes wrong

**Comment by TuxSH** [comment]
Could you try moving the nested functions to not have nested functions? (adding a prefix to those if necessary).

LGTM otherwise ( ͡° ͜ʖ ͡°). (should be squashed on merge)

**Comment by LiquidFenrir** [comment]
well the functions are only for increasing readabilty in the loop/button pressing handling, their call can easily be replaced by their body since they are so short
putting them outside would require using globals or pointer, overall dirtier imo

**Comment by LiquidFenrir** [comment]
This has the function calls replaced with their bodies to avoid nesting them, see if that's good to you if you really want to avoid them: https://github.com/LiquidFenrir/Luma3DS/commit/b7e01fc409ab0e23a740db5d1c4c915b2e020f7d

**Comment by JorgeProGamer** [comment]
Hola a todos, tengo una propuesta para vosotros, solo es una idea que sería muy buena para el Online de Pokémon, un filtro que solo permitiera que te apareciesen usuarios en transeúntes del país que tu quieras, ejemplo: siempre cuando te conectas, te aparece gente de muchas nacionalidades en transeúntes, que tal si pudieras elegir de que país recibir gente? (Only Pokémon X/Y Pokémon Omega Rubí y Zafiro Alfa, y Pokémon Sol y Luna, y próximos), estoy dispuesto a haceros una donación de 20 dolares cuando el proyecto este terminado.

**Comment by Shadow322** [comment]
English plez

**Comment by JorgeProGamer** [comment]
Sorry, i don´t speak english fluency, and i hate use google translate, aurora wright, please, answer me, you speak italian, that is similar to spanish.

**Comment by fincs** [comment]
[sic]
> Hello everyone, I have a proposal for you guys, it's an idea that would be very nice for Pokémon online, a filter that would only allow passerby users in the country you want to show up, example: everytime you connect, a bunch of people from different countries show up, what if you could choose what country to show people from? (Only Pokémon X/Y Pokémon Omega Ruby and Alpha Sapphire, and Pokémon Sun and Moon, and upcoming titles), I'm willing to donate 20 dollars when the project is finished.

**Comment by Derek1199** [comment]
^^^^^^^  Ye

**Comment by JorgeProGamer** [comment]
fincs Wow, muy buena traducción, nunca pensé que alguien acá hablara español, muchas gracias! :D

**Comment by ghost** [comment]
Porque borraron mi comment?

**Comment by AnalogMan151** [comment]
How does this map the memory? It doesn't seem to be the same as a gdb memory map or NTR memory map.

**Comment by urherenow** [comment]
Github isn't a forum. That's a question for GBAtemp

**Comment by LiquidFenrir** [comment]
L. 111-112 https://github.com/AuroraWright/Luma3DS/pull/877/files#diff-fe737d8f440a5bde6fbb47f90b968884R111

didnt really look at gdb or ntr for this

**Pull request merged**
