### PR TITLE
-Werror turns warnings into errors, and doesn't compile

### PR DESCRIPTION
**Pull request by Multimegamander**

### CODE REVIEW

**Comment by urherenow** [comment]
So fix your problem instead of trying to hide it. Luma3DS compiles just fine, as-is.

**Comment by Multimegamander** [comment]
Luma doesn't compile as-is https://www.youtube.com/watch?v=MQusAl7Z7Aw

**Comment by oreo639** [comment]
https://github.com/AuroraWright/Luma3DS/issues/1248
Besides how would removing -Werr fix that? It would still fail to link due to undefined refrences.

**Comment by urherenow** [comment]
Yes it does. Update your libraries. Dkp-pacman doesn’t always have the latest.

**Comment by fincs** [comment]
Clarification: There is no such thing as a "latest" version of libctru that isn't in pacman. There is however a development/work-in-progress branch which hasn't been released yet. And Luma3DS also hasn't had a stable release yet, so expect things like this to happen with interdependencies with prerelease stuff. Note that you don't need to build Luma yourself if you want to help iron out bugs, there is a public nightly service iirc.

**Pull request closed without merging**
