### PR TITLE
removed eshop patch, this fixed the 'updated needed' thing

### PR DESCRIPTION
**Pull request by RShadowhand**
Confirmed for working. Commented the patch out until it's looked into better.

### CODE REVIEW

**Comment by TuxSH** [comment]
There are too much commits. When you push to your own branch it affects the pull request.

**Comment by RShadowhand** [comment]
Wtf, you're right.
How to fix? :P

**Comment by Hartie95** [comment]
Use A branch in your Fork for Pull requests, then only this branch will be used for the pr and your commits to the master will not affect it.

**Comment by RShadowhand** [comment]
Closing due to github.com noobness on my end.

**Pull request closed without merging**
