### PR TITLE
Add compile time font selection from Godmode9

### PR DESCRIPTION
**Pull request by trbocode**
Works fine on my New 3DS.

### CODE REVIEW

**Comment by potjesoep** [comment]
I would love for this to be added but i think it has a higher chance of being accepted if the commit messages were a bit more professional

**Comment by arbingordon** [comment]
Or just squash all of the commits into one, that might help.

**Comment by ghost** [comment]
You might wanna rename some of your commits... (@creeperlwd)

**Comment by ankushg** [comment]
Seems like all this needs is a squash and merge to fix the commit history issues...

**Comment by Margen67** [comment]
@trbocode

**Comment by jonirrings** [comment]
seems you need a rebase to fix your commit history:joy:

**Comment by Margen67** [comment]
Tell that to @trbocode this PR has been dead for 3 months

**Comment by trbocode** [comment]
Sorry, I haven't had the time... I have time on tuesday. Merges fine I belive

**Pull request closed without merging**
