### PR TITLE
Add volume slider override

### PR DESCRIPTION
**Pull request by PabloMK7**
Adds an option in Rosalina to override the volume slider, which persists between reboots.
Since the override relies on Rosalina being present, this feature is not available in DS/TWL mode, older FW versions or Safe Firm.

Known issues:
- Modifying the volume through rosalina makes the console take longer to shut down, regarless of enabling the feature, disabling it, or changing the volume.  (Maybe @profi200 can shed some light into this.)

### CODE REVIEW

**Comment by PabloMK7** [comment]
Closes #1913

**Comment by profi200** [comment]
I didn't observe longer shutdown times when i tested this via a regular homebrew app.

My first thought was maybe you accidentally keep the service session open or something. This could happen with this return:
https://github.com/LumaTeam/Luma3DS/pull/1973/files#diff-e1b9ec12217edfe7842db4e7fce43b8acbef8f6d1433953c814056a9a811f92eR403

**Comment by PabloMK7** [comment]
> I didn't observe longer shutdown times when i tested this via a regular homebrew app.
> 
> My first thought was maybe you accidentally keep the service session open or something. This could happen with this return: https://github.com/LumaTeam/Luma3DS/pull/1973/files#diff-e1b9ec12217edfe7842db4e7fce43b8acbef8f6d1433953c814056a9a811f92eR403

This would cause the menu to show "Failed: 0xFFFFFFFF" which isn't the case. That check is just a failsafe to never go above -20

**Comment by profi200** [comment]
Ah, then i don't know. Maybe something about the way Luma handles sysmodule threads while Rosalina is active. As said i didn't have issues while testing this with a regular .3dsx app.

**Comment by gannon345** [comment]
I compiled the volumeoverride branch tonight to test it. Confirmed, it does take a bit longer to shut down fully, but seems like an acceptable compromise, at least for me. If you're able to determine a fix I'll be happy to reclone and build again to test. I don't really know the coding side behind this, but I'll be happy to help if I can.

Other than the shutdown length, I haven't noticed any issues so far.

**Comment by gannon345** [comment]
Also, not sure if this is helpful, but there's a custom build of Luma 10.3 on Gamebrew that also has volume control in the Rosalina menu.

https://www.gamebrew.org/wiki/Unofficial_Luma_3DS

It's pretty unstable, tended to crash during games, but I note it did not have the long shutdown time. Download link is here: https://gbatemp.net/download/luma-10-3-with-night-light-and-quick-switchers.35619/download

Don't know if it helps but maybe there's something in the files there you could compare to narrow in on the shutdown problem.

**Comment by gannon345** [comment]
Okay, strangely my 2DS XL is now shutting down normally again, no more delay. Not sure why. Was just dinking around with the handheld, testing a few games and after playing off and on for some days with the volumecontrol build and the shutdown delay just... stopped. I have no idea why or what changed.

Only thing I've done that could have changed anything system-wise was running TWPatch to change my NDS settings. But I'm at a loss. It's a good thing, but no idea what changed.

**Comment by TuxSH** [comment]
lgtm, will test later

**Pull request merged**
